name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2    
    - name: qmake
      run: qmake -r CONFIG+=debug_and_release
      working-directory: ./src
    - name: make
      run: make
      working-directory: ./src
